In [1]:
import numpy as np
i2 = np.eye(3)
i2

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [2]:
np.savetxt('F:\My Projects\Python work\Flask and numpy works/numpy code\eye.txt',i2)

In [3]:
c,v=np.loadtxt('../mansoor.csv',delimiter=',', usecols=(0,3),unpack=True)
print(c,"===",v)

[ 1.  2.  3.  4.  5.] === [ 11.  22.  33.  44.  55.]


In [4]:
c,v=np.loadtxt('../mansoor.csv',delimiter=',',usecols=(0,3),unpack=True)
vwap=np.average(c,weights=v)
print("VWAP=",vwap)

VWAP= 3.66666666667


In [5]:
print("mean=",np.mean(c))

mean= 3.0


In [6]:
c,v=np.loadtxt('../mansoor.csv',delimiter=',',usecols=(0,3),unpack=True)

In [7]:
print("highest =", np.max(c))
print("lowest =", np.min(c))


highest = 5.0
lowest = 1.0


In [8]:
t = np.arange(len(c))
t

array([0, 1, 2, 3, 4])

In [9]:
print("twap =", np.average(c, weights=t))

twap = 4.0


In [10]:
print("Spread high price", np.ptp(c))

Spread high price 4.0


In [11]:
print("Spread high price", np.ptp(v))

Spread high price 44.0


In [12]:
print("highest =", np.max(c))
print("lowest =", np.min(c))
print((np.max(c) + np.min(c)) /2)
print("Spread high price", np.ptp(c))
# print("Spread low price", np.ptp(c))

highest = 5.0
lowest = 1.0
3.0
Spread high price 4.0


In [13]:
print("highest =", np.max(v))
print("lowest =", np.min(v))
print((np.max(v) + np.min(v)) /2)
print("Spread high price", np.ptp(v))
# print("Spread low price", np.ptp(v))

highest = 55.0
lowest = 11.0
33.0
Spread high price 44.0


In [14]:
N=len(c)
print("Middle value",(N-1)/2)

Middle value 2.0


In [15]:
mid=np.median(c) #The most middle value is called Median.
mid

3.0

In [16]:
mid2=np.median(v)
mid2

33.0

In [17]:
print("variance =", np.var(v))

variance = 242.0


In [19]:
print("variance from definition =", np.mean((v - v.mean())**2))

variance from definition = 242.0


In [20]:
# diff() function that returns an
# array that is built up of the difference between two consecutive 
# array elements

In [21]:
difference=np.diff(c)
difference

array([ 1.,  1.,  1.,  1.])

In [22]:
returns = np.diff(c)/c[:-1]
returns

array([ 1.        ,  0.5       ,  0.33333333,  0.25      ])

In [23]:
stand=np.std(returns)
stand

0.29092166757851962

0.29092166757851962

In [24]:
logreturns = np.log(c)
logreturns

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791])

In [25]:
logreturns = np.diff(np.log(c))
logreturns

array([ 0.69314718,  0.40546511,  0.28768207,  0.22314355])

In [26]:
posretindices = np.where(returns > 0.3) #return the index of right condition
print("Indices with positive returns", posretindices)

Indices with positive returns (array([0, 1, 2], dtype=int64),)


In [27]:
print(np.take(c,np.where(c<3)))

[[ 1.  2.]]


In [28]:
returns[posretindices]

array([ 1.        ,  0.5       ,  0.33333333])

In [29]:
annual_volatility = np.std(logreturns)/np.mean(logreturns)
annual_volatility = annual_volatility / np.sqrt(1./252.)
print(annual_volatility)

7.10811183512


In [30]:
print("Monthly volatility", annual_volatility * np.sqrt(1./12.))

Monthly volatility 2.05193514072
