In [1]:
import numpy as np
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c
numpysum(10)
print(numpysum(10))


[  0   2  12  36  80 150 252 392 576 810]


In [2]:
a = np.arange(5)
a.dtype

dtype('int32')

In [3]:
a.shape

(5,)

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [6]:
n = np.array([np.ones(2), np.zeros(2)])
n

array([[ 1.,  1.],
       [ 0.,  0.]])

In [7]:
n = np.array([np.arange(1,3), np.arange(3,5)])
n

array([[1, 2],
       [3, 4]])

In [8]:
n = np.array([[1,2],[3,4]])
n

array([[1, 2],
       [3, 4]])

In [9]:
n[1,0]

3

In [10]:
n[0,1]

2

In [11]:
n[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [12]:
n[-1::-1]

array([[3, 4],
       [1, 2]])

In [15]:
n = np.array(n,dtype=bool)
n

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [20]:
n = np.array([np.ones(2),np.zeros(2)],dtype=bool)
n

array([[ True,  True],
       [False, False]], dtype=bool)

In [25]:
a = np.array([1, 2, 3], dtype=complex)
a

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [55]:
 x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
 x['b']

array([2, 4])

In [56]:
x = np.array(np.mat('1 2; 3 4'))
x

array([[1, 2],
       [3, 4]])

In [57]:
x = np.array(np.mat('1 2 3; 3 4 6'),subok=True)
x

matrix([[1, 2, 3],
        [3, 4, 6]])

In [58]:
x = np.arange(0,7,dtype='f')
x


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.], dtype=float32)

In [59]:
x.dtype.itemsize

4

In [60]:
np.dtype('f')

dtype('float32')

In [61]:
np.dtype('f8')

dtype('float64')

In [62]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'uint32', 'Int32', 'UInt32', 'i4', 'u4', 'int64', 'uint64', 'Int64', 'UInt64', 'i8', 'u8', 'int16', 'uint16', 'Int16', 'UInt16', 'i2', 'u2', 'int8', 'uint8', 'Int8', 'UInt8', 'i1', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 

In [63]:
t = np.dtype('Float64')
t.char

C:\Users\Mansoor\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


'd'

In [64]:
t.type

numpy.float64

In [65]:
t.str

'<f8'

In [66]:
import numpy as np
a = np.arange(5)
print(a.dtype)

int32


In [67]:
a

array([0, 1, 2, 3, 4])

In [68]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price',
np.float32)])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [69]:
t['name']

dtype('<U40')

In [70]:
t['numitems']

dtype('int32')

In [71]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13,
2.72)], dtype=t)
itemz

array([('Meaning of life DVD', 42,  3.1400001 ),
       ('Butter', 13,  2.72000003)], 
      dtype=[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [72]:
a = np.array([('Hello',9,8.88)])
a

array([['Hello', '9', '8.88']], 
      dtype='<U5')

In [73]:
a = np.arange(9)
a[3:]

array([3, 4, 5, 6, 7, 8])

In [74]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [75]:
b = np.arange(10).reshape(5,2)
b.shape

(5, 2)

In [76]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
b = np.ones(64,dtype=int).reshape(8,8)
b

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [78]:
b[:,::2] = 0

In [79]:
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [80]:
c = np.arange(36).reshape(3,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [81]:
c[0,1,:]

array([4, 5, 6, 7])

In [82]:
c[2,2,2]

34

In [83]:
c[1,1,1]

17

In [84]:
d = np.arange(0,64)
d.itemsize

4

In [85]:
c[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
c[0,2,2]

10

In [87]:
c[:,2,2]

array([10, 22, 34])

In [88]:
c[0,:,1]

array([1, 5, 9])

In [89]:
c[0,:,-1]

array([ 3,  7, 11])

In [90]:
c[0,::-1,-1]

array([11,  7,  3])

In [91]:
c[::-1,::-1,::-1]

array([[[35, 34, 33, 32],
        [31, 30, 29, 28],
        [27, 26, 25, 24]],

       [[23, 22, 21, 20],
        [19, 18, 17, 16],
        [15, 14, 13, 12]],

       [[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]])

In [92]:
c[0,::2,-1]

array([ 3, 11])

In [93]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [94]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [95]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [96]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [97]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [98]:
c.shape = (3,4,3)

In [99]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [100]:
c.shape = (3,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [101]:
c.transpose()

array([[[ 0, 12, 24],
        [ 4, 16, 28],
        [ 8, 20, 32]],

       [[ 1, 13, 25],
        [ 5, 17, 29],
        [ 9, 21, 33]],

       [[ 2, 14, 26],
        [ 6, 18, 30],
        [10, 22, 34]],

       [[ 3, 15, 27],
        [ 7, 19, 31],
        [11, 23, 35]]])

In [102]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [103]:
c.resize(3,12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [104]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
h = np.arange(9).reshape(3,3)
h = h**2
h

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [106]:
np.hstack((m,h))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25],
       [ 6,  7,  8, 36, 49, 64]])

In [107]:
np.concatenate((m,h),axis=1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25],
       [ 6,  7,  8, 36, 49, 64]])

In [108]:
m[:,0]

array([0, 3, 6])

In [109]:
np.vstack((m,h))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [110]:
np.concatenate((m,h),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [111]:
np.dstack((m,h))

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  4]],

       [[ 3,  9],
        [ 4, 16],
        [ 5, 25]],

       [[ 6, 36],
        [ 7, 49],
        [ 8, 64]]])

In [112]:
m = np.arange(27).reshape(3,3,3)
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [113]:
h = m**2
h

array([[[  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64]],

       [[ 81, 100, 121],
        [144, 169, 196],
        [225, 256, 289]],

       [[324, 361, 400],
        [441, 484, 529],
        [576, 625, 676]]])

In [114]:
np.hstack((m,h))

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 81, 100, 121],
        [144, 169, 196],
        [225, 256, 289]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [324, 361, 400],
        [441, 484, 529],
        [576, 625, 676]]])

In [115]:
np.vstack((m,h))

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64]],

       [[ 81, 100, 121],
        [144, 169, 196],
        [225, 256, 289]],

       [[324, 361, 400],
        [441, 484, 529],
        [576, 625, 676]]])

In [116]:
np.dstack((m,h))

array([[[  0,   1,   2,   0,   1,   4],
        [  3,   4,   5,   9,  16,  25],
        [  6,   7,   8,  36,  49,  64]],

       [[  9,  10,  11,  81, 100, 121],
        [ 12,  13,  14, 144, 169, 196],
        [ 15,  16,  17, 225, 256, 289]],

       [[ 18,  19,  20, 324, 361, 400],
        [ 21,  22,  23, 441, 484, 529],
        [ 24,  25,  26, 576, 625, 676]]])

In [117]:
np.column_stack((m,h))

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 81, 100, 121],
        [144, 169, 196],
        [225, 256, 289]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [324, 361, 400],
        [441, 484, 529],
        [576, 625, 676]]])

In [118]:
np.row_stack((m,h))

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64]],

       [[ 81, 100, 121],
        [144, 169, 196],
        [225, 256, 289]],

       [[324, 361, 400],
        [441, 484, 529],
        [576, 625, 676]]])

In [119]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
np.hsplit(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [121]:
a.shape = (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [123]:
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [125]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [126]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [127]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
np.hsplit(m,3)

[array([[[ 0,  1,  2]],
 
        [[ 9, 10, 11]],
 
        [[18, 19, 20]]]), array([[[ 3,  4,  5]],
 
        [[12, 13, 14]],
 
        [[21, 22, 23]]]), array([[[ 6,  7,  8]],
 
        [[15, 16, 17]],
 
        [[24, 25, 26]]])]

In [129]:
np.vsplit(m,3)

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]), array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]), array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]

In [130]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [132]:
np.dsplit(m,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [133]:
m.ndim

3

In [134]:
m.size

27

In [135]:
m.itemsize

4

In [136]:
m.nbytes

108

In [137]:
m.real

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
m.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [139]:
m.flat[[0,1,9,13]]

array([ 0,  1,  9, 13])

In [140]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [141]:
m.tolist() #Convert to a list

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
 [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
 [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]

In [142]:
m.astype(float) #convert data type

array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.]],

       [[  9.,  10.,  11.],
        [ 12.,  13.,  14.],
        [ 15.,  16.,  17.]],

       [[ 18.,  19.,  20.],
        [ 21.,  22.,  23.],
        [ 24.,  25.,  26.]]])